angular.module('academy').config(function($translateProvider) {
  $translateProvider.translations('en', {
    //header-desktop
    ABOUT_US: 'About us',
    FEATURES: 'Features',
    PRICING: 'Pricing',
    FACULTY:'Faculty',
    LIBRARY: 'Library',
    HOME: 'Home',
    SHOW_FULL_TEXT: 'Show full text',
    COURSE_CATEGORIES: 'Course categories',
    HP_BLOCK_TITLE: 'Course categories',
    HP_NAV_ITEM_1: 'All courses',
    HP_NAV_ITEM_2: 'Data & CRM',
    HP_NAV_ITEM_3: 'Health',
    HP_NAV_ITEM_4: 'HR',
    HP_NAV_ITEM_5: 'Internet & organization',
    HP_NAV_ITEM_6: 'Management skills',
    HP_NAV_ITEM_7: 'Oral communication',
    HP_NAV_ITEM_8: 'Office productivity',
    HP_NAV_ITEM_9: 'Online marketing',
    HP_NAV_ITEM_10: 'Personal effectiveness',
    HP_NAV_ITEM_11: 'Project',
    HP_NAV_ITEM_12: 'Sales',
    HP_NAV_ITEM_13: 'Written communication',
    HP_NAV_ITEM_14: 'Social media',
    BECOME_AN_INSTRUCTOR: 'Become an instructor',
    FOR_ORGANIZATIONS: 'For organizations',
    SIGN_IN: 'Sign in',
    SIGN_UP: 'Sign up',
    SIGN_OUT: 'Sign out',
    ACCOUNT: 'Account',
    MY_COURSES: 'My courses',
    MY_DASHBOARD: 'My dashboard',
    PROFILE_SETTINGS: 'Profile settings',
    SWITCH_ACADEMY: 'Switch Academy',
    STUDYTUBE_ACADEMY: 'Studytube academy',
    HVDS_ACADEMY: 'HVDS academy',
    //header-mobile
    NAVIGATION: 'Navigation',
    BROWSE: 'Browse',
    USER_MENU: 'User menu',
    // footer
    PAGES: 'Pages',
    PF_MENU_P1_1: 'Home',
    PF_MENU_P1_2: 'Pricing',
    PF_MENU_P1_3: 'Courses',
    PF_MENU_P1_4: 'Faculty',
    BROWSE_COURSES: 'Browse courses',
    SUPPORT: 'Support',
    PF_MENU_P2_1: 'Terms & conditions',
    PF_MENU_P2_2: 'Terms & conditions #2',
    PF_MENU_P2_3: 'Privacy regulations',
    CONNECT: 'Connect',
    CONTACTS: 'Contact us',
    PRESSDOC: 'Pressdoc',
    VAT: 'VAT',
    KVK: 'KVK',
    //landing page
    LANDING_TITLE: 'Studytube',
    LANDING_TITLE_DESCRIPTION: 'Increase the performance of employees and your business!',
    JOIN_STUDYTUBE: 'Join studytube',
    PRIORITY: 'priority',
    CONTENT_SECTION_TITLE_SECONDARY: 'To provide highest possible online courses',
    LANDING_PITCH_TEXT: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa ullam, cumque ratione amet reprehenderit perspiciatis. Nobis laborum eveniet libero assumenda, maiores adipisci ratione molestiae ipsa architecto tempore minus commodi a.',
    LANDING_PRIORITY_LIST_1: 'Personalized Experience',
    LANDING_PRIORITY_LIST_2: 'Result driven learning',
    LANDING_PRIORITY_LIST_3: 'Courses from top experts only',
    LANDING_PRIORITY_LIST_4: 'Online learning made social and fun',
    LANDING_PRIORITY_LIST_5: 'All courses are created with love',
    FEATURED_COURSES: 'Featured courses',
    BROWSE_ALL: 'Browse all',
    TESTIMONIALS: 'Testimonials',
    STUDYTUBE_IN_MEDIA: 'Studytube in media',
    ADV_SUBSCRIPTION: 'Master hundreds of courses only for <strong>€49</strong> per month.',
    START_SUBSCRIPTION: 'Start subscription',
    //become-expert page
    BECOME_EXPERT_PAGE_TITLE: 'Interested in becoming one of our experts?',
    BECOME_EXPERT_PAGE_DESCRIPTION: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro quaerat nemo odio, tempora molestiae quo vel harum non cupiditate vero! Accusantium a repellendus dolor corrupti. Quisquam debitis consequatur totam culpa.',
    NAME: 'Name',
    EXPERTIZE: 'Expertise',
    EMAIL_ADDRESS: 'Email address',
    PHONE_NUMBER: 'Phone number',
    GET_FREE_BROCHURE: 'Get free brochure',
    PROCESSING: 'Processing...',
    REQUIRED: 'Required',
    EXPERT_BROCHURE_SENT_MESSAGE: 'Thank you for your interest!<br>We will send you our awesome brochure in a short time.',
    //pricing page
    PRICING_TITLE: 'Studytube comes in<br><strong>two flavours!</strong>',
    FLAVOUR: 'Flavour',
    FLAVOUR_TITLE_1: 'All You Can Learn',
    FLAVOUR_TITLE_2: 'Pay Per Course',
    CS_TITLE_STROKED_TEXT_1: 'Access all courses for a small monthly fee',
    CS_TITLE_STROKED_TEXT_2: 'What\'s included',
    CS_TITLE_STROKED_TEXT_3: 'Lifetime access',
    PRICING_PLAN_1: 'With “All you can learn” subscription you will get unlimited access to all of our courses.',
    PRICING_PLAN_2: 'You buy a single course, and get access for the rest of your life.',
    PER_MONTH: 'per month',
    PER_COURSE: 'per course',
    CREATE_FREE_ACCOUNT: 'Create free account',
    PRICING_PLAN_EXTRA: 'More than $20,000 worth of content',
    PRICING_FEATURE_1: 'Learn what you want, when you want, from our entire library.',
    PRICING_FEATURE_2: 'New courses are added to our library weekly - so the value of your membership keeps growing',
    PRICING_FAQ_TITLE_1: 'How many courses can I take?',
    PRICING_FAQ_TITLE_2: 'Can I cancel my subscription at any time?',
    PRICING_FAQ_BODY_1: 'As many as you want! Studytube subscription includes unlimited access to our entire library of courses.',
    PRICING_FAQ_BODY_2: 'Minimum duration of the subscription is a 3 months. After that you can cancel at any time.',
    START_SUBSCRIPTION_NOW: 'Start subscription now',
    //about
    ABOUT_COMPANY: 'About company',
    OUR_VALUES: 'Our values',
    CAREERS: 'Careers',
    COMPANY_TITLE: 'We are here to change the world<br>of <strong>corporate learning!</strong>',
    VALUES_TITLE: 'Driven by <strong>ideals!</strong>',
    CAREERS_TITLE: 'Become one of <strong>us!</strong>',
    CONTACT_TITLE: 'Drop us a <strong>line.</strong>',
    OUR_MISSION: 'Our mission',
    MEET_TEAM: 'Meet the team',
    ABOUT_BLOCK_TITLE_2: 'Over 20',
    ABOUT_BLOCK_TEXT_1: 'Launched from Homam’s dorm room in the University of Maastricht',
    ABOUT_BLOCK_TEXT_2: 'Grown to an exceptional team of more than 20 crazy highly-skilled people',
    ABOUT_BLOCK_TEXT_3: 'Users got smarter with StudyTube so far',
    OUR_MISSION_TEXT: 'StudyTube is committed to bringing the best online learning experience to every member of the goal workforce, to built a place where professionals can learn anything that makes them more productive and successful in their professional career.',
    MEET_TEAM_TEXT: 'Dreamers, Designers, Computer Geeks, E-Learning People... <br>Handful of talented people.',
    VALUES_TITLE_SECONDARY_1: 'Company values',
    VALUES_TITLE_SECONDARY_2: 'Course values',
    COMPANY_VALUES_ITEM_1: 'Empathethic',
    COMPANY_VALUES_ITEM_2: 'Simple',
    COMPANY_VALUES_ITEM_3: 'Smart',
    COMPANY_VALUES_ITEM_4: 'Challenging',
    COMPANY_VALUES_ITEM_5: 'Ambitious',
    COMPANY_VALUES_ITEM_1_DESCRIPTION: 'Distill to the meaningful and balanced.',
    COMPANY_VALUES_ITEM_2_DESCRIPTION: 'Distill to the meaningful and balanced.',
    COMPANY_VALUES_ITEM_3_DESCRIPTION: 'Distill to the meaningful and balanced.',
    COMPANY_VALUES_ITEM_4_DESCRIPTION: 'Distill to the meaningful and balanced.',
    COMPANY_VALUES_ITEM_5_DESCRIPTION: 'Distill to the meaningful and balanced.',
    COURSE_VALUES_ITEM_1: 'Creativity & Fun',
    COURSE_VALUES_ITEM_2: 'Result oriented',
    COURSE_VALUES_ITEM_3: 'Personal',
    COURSE_VALUES_ITEM_1_DESCRIPTION: 'We strive to ensure that each course is fun to follow. It is an online course much more difficult to increase the motivation and maintain than a classroom course. Attention of a student It is very important that your course alternate methods (videos, images, text, questions) that arouse interest in order to reduce the risk of diversion and increase motivation. So Incorporate the theme of your course in videos, tell stories and give many examples you present energetic, enthusiastic and confident.',
    COURSE_VALUES_ITEM_2_DESCRIPTION_1: 'How well your course is also content: really only be a success when students show new behavior. In other words, not only to ensure that students gain new knowledge and insights, but also that they adapt their behavior on this knowledge and that they train skills. You want to prevent students stuck in old habits. Therefore, make sure that you:',
    COURSE_VALUES_ITEM_2_DESCRIPTION_2: '<strong>Sufficient finds connections between theory and practice</strong>',
    COURSE_VALUES_ITEM_2_DESCRIPTION_3: 'Try to give the (theoretical) explanation you give. Much as possible examples and / or practical situations Also try to look for images that illustrate this example well. When issuing an example.',
    COURSE_VALUES_ITEM_2_DESCRIPTION_4: '<strong>Specific enough practical questions.</strong>',
    COURSE_VALUES_ITEM_2_DESCRIPTION_5: 'A question is not meant to hear about anyone, but in order to think about a situation in practice. The student Think of a course on the prevention of conflict in the workplace to a question like: "Jack is a web developer. He has problems with his internet connection. How can he be his supervisor - who is always very busy and would rather not be disturbed - the best approach here about? ".',
    COURSE_VALUES_ITEM_2_DESCRIPTION_6: '<strong>The student shows work on a final product.</strong>',
    COURSE_VALUES_ITEM_2_DESCRIPTION_7: 'The student has not only new knowledge and insights obtained after completion of the course, but he or she also has something tangible in hand to user know into practice immediately. Think of a sales course to making a sales pitch or a course on presentation techniques on a script and presentation slides.',
    COURSE_VALUES_ITEM_3_DESCRIPTION_1: 'Courses that are tailored to the individual delivering the highest results. One of the main features of Study Tube is also the fact that courses \'adaptive\' offer. In other words, when a student question in the course answers wrong - and therefore the part apparently not fully understand - he gets extra content offered to ensure that he or she still comes to the same knowledge as someone who is the same part or directly understands. It is also important that you keep the \'distance\' between you (the expert) and the student as much as possible and avoid as much as possible formal language. In short, so make sure that you:',
    COURSE_VALUES_ITEM_3_DESCRIPTION_2: '<strong>For each topic one or more adaptive paths create.</strong>',
    COURSE_VALUES_ITEM_3_DESCRIPTION_3: 'These are additional learning routes which you repeat the learned knowledge in a different form or simplified explains.',
    COURSE_VALUES_ITEM_3_DESCRIPTION_4: '<strong>Gives feedback on each answer option.</strong>',
    COURSE_VALUES_ITEM_3_DESCRIPTION_5: 'Therefore do you play on the individual development of a student and make sure that he / she can memorize the content.',
    COURSE_VALUES_ITEM_3_DESCRIPTION_6: '<strong>The student appeals to you in the form.</strong>',
    COURSE_VALUES_ITEM_3_DESCRIPTION_7: 'In this way, the student gets a lot more sense that there is little distance between him or her and the expert who teaches the course.',
    COURSE_VALUES_ITEM_3_DESCRIPTION_8: '<strong>Gives examples which connect to the experiences of the student.</strong>',
    COURSE_VALUES_ITEM_3_DESCRIPTION_9: 'Think carefully about exactly who your target audience is and tailor your examples to them. A doctor is of a perception other than a lawyer or a web developer.',
    ALL_POSITIONS: 'All positions',
    APPLY_POSITION: 'Apply for this position',
    CAREERS_TITLE_SECONDARY_1: 'We need new people',
    CAREERS_TITLE_SECONDARY_1_DESCRIPTION: 'StudyTube is committed to bringing the best online learning experience to every member of the goal workforce, to built a place where professionals can learn anything that makes them more productive and successful in their professional career.',
    CONTACT_TITLE_SECONDARY_1: 'We are we',
    CONTACT_TITLE_SECONDARY_1_DESCRIPTION: 'StudyTube HQ are in a nice and cozy penthouse right in the middle of Amsterdam.  We also have a couple offices around the world.',
    //auth
    LOG_IN: 'Log in',
    HAVE_AN_ACCOUNT: 'Already a member?',
    PASSWORD: 'Password',
    PASSWORD_CONFIRMATION: 'Password (confirmation)',
    FORGOT_PASSWORD: 'Forgot password?',
    LET_ME_IN: 'Let me in',
    INVALID_EMAIL: 'Invalid email...',
    INVALID_PASSWORD: '... or password',
    NOT_HAVE_ACCOUNT: 'Do not have an account yet?',
    USERNAME: 'Username',
    CREATE_ACCOUNT: 'Create an account',
    //courses
    COURSES_TITLE: 'Buy all you can learn subscription for <strong>€49</strong> per month!',
    JOIN_STUDYTUBE_NOW: 'Join Studytube now',
    BY_CATEGORY: 'By category',
    BY_CATEGORY_INSTRUCTOR: 'By category',
    BY_CATEGORY_COURSES: 'By category',
    LOAD_MORE_INSTRUCTORS: 'load more',
    LOAD_MORE_COURSES: 'load more',
    FIND_INSTRUCTOR: 'Find an instructor',
    FIND_COURSE: 'Find a course',
    PLAY_VIDEO: 'Play video',
    LIFETIME_ACCESS: 'Lifetime access',
    USERS: 'users',
    BUY_FOR: 'Buy for',
    ADD_COURSE: 'Add',
    COURSE_INSTALLED: 'Installed',
    COURSES_ITEM_TITLE_1: 'Instructors',
    COURSES_ITEM_TITLE_2: 'About',
    COURSES_ITEM_TITLE_3: 'Curriculum',
    COURSES_ITEM_TITLE_4: 'Similar courses',
    COURSE_COMING_SOON: '(Coming soon)',
    PREVIEW: 'preview',
    READ_FULL_TEXT: 'Read full text',
    CONFIRM_PURCHASE: 'Confirm purchase',
    REDEEM_COUPON: 'Redeem a coupon',
    INVALID_CODE: 'Invalid coupon code',
    APPLY_CODE: 'Apply code',
    COUPON_ACTIVATED: 'Coupon code successfully activated',
    SUBTOTAL: 'Subtotal',
    TOTAL: 'Total',
    PROCEED: 'Proceed',
    AGREE_TERM_PURCHASING_COURSES: 'Payment will bring you to the 3rd party payment provider. By clicking the proceed you agree to our <a href="/legal/conditions" class="fbc-legal__link" target="_blank">Terms & Conditions</a> on purchasing courses.',
    //instructors
    INSTRUCTORS_TITLE: 'Meet our faculty',
    ALL_EXPERTS: 'All experts',
    MEMBER_OF: 'Member of',
    INSTRUCTOR_TITLE_SECONDARY_1: 'Publications',
    INSTRUCTOR_TITLE_SECONDARY_2: 'Teaching',
    INSTRUCTOR_TITLE_SECONDARY_3: 'Reference',
    INSTRUCTOR_TITLE_SECONDARY_4: 'Testimonials',
    INSTRUCTOR_TITLE_SECONDARY_5: 'Want a customized learning for your organization',
    SEE_SOURCE: 'See source',
    COMPANY_NAME: 'Company name',
    YOUR_NAME: 'Your name',
    CANNOT_EMPTY: 'Cannot be empty',
    YOUR_ROLE: 'Your role',
    YOUR_PHONE_NUMBER: 'Your phone number',
    YOUR_EMAIL: 'Your email',
    I_WOULD_LIKE: 'I would like...',
    I_WOULD_LIKE_ITEM_1: 'to get customized course for my organization',
    I_WOULD_LIKE_ITEM_2: 'to get a call back',
    I_WOULD_LIKE_ITEM_3: 'to make an appointment',
    I_WOULD_LIKE_ITEM_4: 'to book an offline training',
    I_WOULD_LIKE_ITEM_5: 'something else',
    YOUR_MESSAGE: 'Your message',
    SEND_MESSAGE: 'Send message',
    //profile
    EDIT_PROFILE: 'Edit profile',
    CURRENT_COURSES: 'Current courses',
    RECOMMENDED_COURSES: 'Recommended courses',
    FINISHED_COURSES: 'Finished courses',
    NO_COURSES_YET: 'You have no courses yet',
    GO_LIBRARY: 'Go to library',
    PROFILE_AVATAR_DESCRIPTION: 'Avatar should be a square image at minimum 300 x 300 px.',
    CHANGE_IMAGE: 'Change image',
    NEW_PASSWORD: 'New password',
    CONFIRM_PASSWORD: 'Confirm new password',
    DISCARD: 'Discard',
    SAVE: 'Save',
    CONTACT_MESSAGE_SENT: 'Message has been sent! Thank you!',
    FREE: 'Free',
    LEGAL_ITEM_1: 'Terms and conditions',
    LEGAL_ITEM_2: 'Privacy regulations',
    CHANGE_PASSWORD: 'Change password',
    CURRENT_PASSWORD: 'Current password',
    //features page
    FEATURES_TITLE: 'What makes us<br><strong>Unique?</strong>',
    FEATURES_SECONDARY_TITLE_1: 'Recognized top experts',
    FEATURES_SECONDARY_TITLE_2: 'Practical and result-oriented courses',
    SEE_ALL_EXPERTS: 'See all experts',
    FEATURES_SECONDARY_TITLE_1_DISCRIPTION: 'Studytube only works with recognised experts in their fields. They are selected on the basis of their field of expertise, experience, reputation and publications.',
    //flash messages
    ALREADY_SUBSCRIBED: 'You already have a subscription',
    BUY_CONTENT_LICENSE_ERROR: 'An error occurred, please try again later.',
    ADD_COURSE_ERROR: 'An error occurred, please try again later.',
    COURSE_NOT_AVAILABLE_ERROR: 'Course is not available now. Please contact us to solve this.'
  });
});